spring.application.name=demo
spring.datasource.url=jdbc:postgresql://ep-fragrant-bar-amwous8s-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4E5gFRIxTOzK
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret=0123456789abcdef0123456789abcdef
security.jwt.expiration-seconds=3600

app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173
app.seed-demo-user=true
